services:
  mack-bot:
    build:
      context: .
      args:
        VERSION: "latest"
    image: mack-bot:latest
    container_name: mack-bot
    restart: unless-stopped
    volumes:
      - ./data:/root/Documents/Mack-Bot
    stdin_open: true
    tty: true
